// Auto-generated by scripts/import-wp.ts — DO NOT EDIT MANUALLY
// Run `npx tsx scripts/import-wp.ts` to regenerate.

export type ImportedProject = {
  key: string;
  title: string;
  slug: string;
  categories: string[];
  image: string | null;
  wpImages: string[];
  externalUrl?: string;
};

export const importedProjects: ImportedProject[] = [
  {
    "key": "dream-cleaning",
    "title": "Dream Cleaning",
    "slug": "dream-cleaning",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2023/12/Screenshot_9-4.png",
      "https://www.imperial-media.ro/wp-content/uploads/2023/12/Screenshot_11-1.png"
    ],
    "externalUrl": "https://www.dreamcleaning.ro"
  },
  {
    "key": "ionut-bogdan-carausu",
    "title": "Ionuț Bogdan-Carăușu",
    "slug": "ionut-bogdan-carausu",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2024/10/Screenshot_7-1.png",
      "https://www.imperial-media.ro/wp-content/uploads/2024/10/Screenshot_8-1.png",
      "https://www.imperial-media.ro/wp-content/uploads/2024/10/Screenshot_10-1.png"
    ],
    "externalUrl": "https://www.ionut-bogdancarausu.ro"
  },
  {
    "key": "botosani-expres",
    "title": "Botosani Expres",
    "slug": "botosani-expres",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2022/12/Screenshot_12.png",
      "https://www.imperial-media.ro/wp-content/uploads/2022/12/Screenshot_11-2.png"
    ]
  },
  {
    "key": "creare-website-asociatia-h-a-p-py",
    "title": "Asociația H.A.P.PY",
    "slug": "creare-website-asociatia-h-a-p-py",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2024/10/Screenshot_22-1.png"
    ],
    "externalUrl": "https://www.asociatia-happy.ro/"
  },
  {
    "key": "asociatia-scut-botosanean",
    "title": "Asociația Scut Botoșănean",
    "slug": "asociatia-scut-botosanean",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2024/10/Screenshot_18-1.png"
    ],
    "externalUrl": "https://www.xn--scutbotonean-5nb500b.ro/"
  },
  {
    "key": "botosaneanul-ro",
    "title": "Botoșăneanul.ro",
    "slug": "botosaneanul-ro",
    "categories": [
      "Dezvoltare Web",
      "Mentenanță web"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2024/10/Screenshot_21-1.png"
    ],
    "externalUrl": "https://www.botosaneanul.ro/"
  },
  {
    "key": "clinica-sfantul-nicolae",
    "title": "Clinica Sfantul Nicolae",
    "slug": "clinica-sfantul-nicolae",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2024/10/Screenshot_16-1.png"
    ],
    "externalUrl": "https://www.clinicasfantulnicolae.ro/"
  },
  {
    "key": "asociatia-b-right-media",
    "title": "Asociatia B-Right Media",
    "slug": "asociatia-b-right-media",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Mentenanță web",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2024/10/Screenshot_21-2.png"
    ],
    "externalUrl": "https://asociatiabrm.ro/"
  },
  {
    "key": "trafyt-ro",
    "title": "Trafyt.ro",
    "slug": "trafyt-ro",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2024/10/Screenshot231520x775.png"
    ],
    "externalUrl": "https://trafyt.ro/"
  },
  {
    "key": "asociatia-autism-botosani",
    "title": "Asociația Autism Botoșani",
    "slug": "asociatia-autism-botosani",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2024/10/Screenshot361520x775.png"
    ],
    "externalUrl": "https://autismbotosani.ro/"
  },
  {
    "key": "dream-movers-botosani",
    "title": "Dream Movers, Botoșani",
    "slug": "dream-movers-botosani",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2024/10/Screenshot411520x775.png"
    ],
    "externalUrl": "https://www.dream-movers.ro"
  },
  {
    "key": "gospodarasul-ro",
    "title": "Gospodarasul.ro",
    "slug": "gospodarasul-ro",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Magazin Online",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2023/04/Screenshot_47-1.png"
    ],
    "externalUrl": "http://www.gospodarasul.ro"
  },
  {
    "key": "fundraising-academy",
    "title": "Fundraising Academy",
    "slug": "fundraising-academy",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2024/10/Screenshot_51-1.png"
    ],
    "externalUrl": "https://fundraisingacademy.ro"
  },
  {
    "key": "asociatia-teona-ariana-2",
    "title": "Asociația Teona Ariana",
    "slug": "asociatia-teona-ariana-2",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2025/09/Screenshot_63-1.webp"
    ],
    "externalUrl": "https://www.teona-ariana.ro"
  },
  {
    "key": "asociatia-teona-ariana",
    "title": "Parohia „Sfânta Cuvioasă Teodora de la Sihla” – Botoșani",
    "slug": "asociatia-teona-ariana",
    "categories": [
      "Branding",
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2025/09/teodora-1474x775.png",
      "https://www.imperial-media.ro/wp-content/uploads/2025/09/Screenshot_145-750x320.png",
      "https://www.imperial-media.ro/wp-content/uploads/2025/09/Screenshot_146-750x320.png"
    ],
    "externalUrl": "https://www.parohiasfteodoradelasihla.ro"
  },
  {
    "key": "transport-marfa-mutari-botosani",
    "title": "Transport Marfă – Mutări Botoșani",
    "slug": "transport-marfa-mutari-botosani",
    "categories": [
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2025/09/Screenshot_147-1520x775.png",
      "https://www.imperial-media.ro/wp-content/uploads/2025/09/Screenshot_149-750x320.png",
      "https://www.imperial-media.ro/wp-content/uploads/2025/09/Screenshot_148-750x320.png"
    ],
    "externalUrl": "https://www.mutaribotosani.ro"
  },
  {
    "key": "group-extra-site-de-prezentare",
    "title": "Group Extra – Site de Prezentare",
    "slug": "group-extra-site-de-prezentare",
    "categories": [
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2025/11/Screenshot_400-1520x775.png",
      "https://www.imperial-media.ro/wp-content/uploads/2025/11/Screenshot_401-750x320.png",
      "https://www.imperial-media.ro/wp-content/uploads/2025/11/Screenshot_402-750x320.png"
    ],
    "externalUrl": "https://www.groupextra.ro"
  },
  {
    "key": "cununa-film",
    "title": "Cununa Film – Site de Prezentare",
    "slug": "cununa-film",
    "categories": [
      "Dezvoltare Web",
      "Mentenanță web",
      "PR & Marketing",
      "Website de Prezentare"
    ],
    "image": null,
    "wpImages": [
      "https://www.imperial-media.ro/wp-content/uploads/2026/01/Screenshot_38-1520x775.png",
      "https://www.imperial-media.ro/wp-content/uploads/2026/01/Screenshot_39-750x320.png",
      "https://www.imperial-media.ro/wp-content/uploads/2026/01/Screenshot_40-750x320.png"
    ],
    "externalUrl": "https://www.cununa-film.ro/"
  }
];
